// ============================================================
// file_writer.rs — File Writing Utility for Agent Team
// ============================================================
//
// This module handles writing generated code to disk as complete
// Rust projects. Each project gets a timestamped directory with
// Cargo.toml, src/main.rs, and README.md.

use chrono::Local;
use std::fs;
use std::io;
use std::path::PathBuf;

/// Represents the output of a project written to disk
pub struct ProjectOutput {
    pub directory: PathBuf,
    pub files_created: Vec<String>,
}

/// Creates a timestamped output directory and writes a complete Rust project
/// Returns the directory path and list of files created
pub fn write_project(
    task_description: &str,
    code: &str,
    task_id: u32,
) -> Result<ProjectOutput, io::Error> {
    // Generate timestamped directory name
    let timestamp = Local::now().format("%Y-%m-%d-%H-%M-%S").to_string();
    let dir_name = format!("agent-team-output-{}", timestamp);
    let dir_path = PathBuf::from(&dir_name);

    // Create directory structure
    fs::create_dir(&dir_path)?;
    let src_dir = dir_path.join("src");
    fs::create_dir(&src_dir)?;

    let mut files_created = Vec::new();

    // Write Cargo.toml
    let cargo_toml_path = dir_path.join("Cargo.toml");
    let cargo_toml_content = generate_cargo_toml(task_description, task_id);
    fs::write(&cargo_toml_path, cargo_toml_content)?;
    files_created.push("Cargo.toml".to_string());

    // Write src/main.rs
    let main_rs_path = src_dir.join("main.rs");
    fs::write(&main_rs_path, code)?;
    files_created.push("src/main.rs".to_string());

    // Write README.md
    let readme_path = dir_path.join("README.md");
    let readme_content = generate_readme(task_description, task_id, &timestamp);
    fs::write(&readme_path, readme_content)?;
    files_created.push("README.md".to_string());

    Ok(ProjectOutput {
        directory: dir_path,
        files_created,
    })
}

/// Generate Cargo.toml content with proper package metadata
fn generate_cargo_toml(task_description: &str, task_id: u32) -> String {
    // Sanitize task description for use in description field
    let sanitized_description = task_description
        .replace("\"", "\\\"")
        .chars()
        .take(100) // Limit description length
        .collect::<String>();

    format!(
        r#"[package]
name = "agent-team-task-{}"
version = "0.1.0"
edition = "2021"
description = "{}"

[dependencies]
"#,
        task_id, sanitized_description
    )
}

/// Generate README.md content with task description and usage instructions
fn generate_readme(task_description: &str, task_id: u32, timestamp: &str) -> String {
    format!(
        r#"# Agent Team Output — Task #{}

**Generated:** {}

**Task:** {}

## How to Run

```bash
cargo run
```

## How to Build

```bash
cargo build --release
```

---

*Generated by agent-team — Multi-Agent Coding Assistant*
"#,
        task_id, timestamp, task_description
    )
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_cargo_toml_generation() {
        let content = generate_cargo_toml("Write a hello world program", 1);
        assert!(content.contains("name = \"agent-team-task-1\""));
        assert!(content.contains("Write a hello world program"));
    }

    #[test]
    fn test_readme_generation() {
        let content = generate_readme("Write a hello world program", 1, "2026-02-18-14-23-05");
        assert!(content.contains("Task #1"));
        assert!(content.contains("Write a hello world program"));
        assert!(content.contains("cargo run"));
    }

    #[test]
    fn test_sanitize_description_with_quotes() {
        let content = generate_cargo_toml("Write a program that prints \"Hello\"", 1);
        assert!(content.contains("prints \\\"Hello\\\""));
    }
}
